language: node_js

sudo: false

node_js:
  - "5"

cache:
  apt: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

before_install:
  # Set Git config
  - git config --global user.name "tianyong90"
  - git config --global user.email "412039588@qq.com"
  - git config --global push.default simple

script:
  - npm install -no-optional

after_script:
  - npm run dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
